spring:
 sendgrid:
  api-key: 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
 cloud:
    vault:
      kv:
        enabled: 'true'
      scheme: http
      token: 00000000-0000-0000-0000-000000000000
 config:
     import: vault://
 datasource:
    url: jdbc:sqlserver://rg-wf.database.windows.net:1433;database=db--budget;user=userDmlBudget;password=us3rDmlBudg3t;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
 application:
    name: gs-vault-config
 security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: IpdYiXcopuxrOm0DqQ381zpdyJ3M3aJa
            client-secret: QyeZ7-6mLSrQQztPeniHFRx3yE30bsDoDgUlBu61YWXG0DcRw3MBdoxgCccLM0FB
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://zebaxthi.us.auth0.com/
