auth0:
  audience: https://zebaxthi.us.auth0.com/api/v2/
azure:
 application-insights:
  instrumentation-key: 0fc69e37-c8bb-4506-b909-80b0550ab8f0
spring:
 sendgrid:
  api-key: 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
 datasource:
  url: jdbc:sqlserver://rg-wf.database.windows.net:1433;database=db--budget;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  username: userDmlBudget
  password: us3rDmlBudg3t
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
 security:
    oauth2:
      resourceserver:
       jwt: 
        issuer-uri: https://zebaxthi.us.auth0.com/
      client:
        registration:
          auth0:
            client-id: IpdYiXcopuxrOm0DqQ381zpdyJ3M3aJa
            client-secret: QyeZ7-6mLSrQQztPeniHFRx3yE30bsDoDgUlBu61YWXG0DcRw3MBdoxgCccLM0FB
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://zebaxthi.us.auth0.com/

 